import { Poppins } from "next/font/google";
import "./globals.css";
import CustomThemeProvider from "@/theme/ThemeProvider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CustomThemeProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </CustomThemeProvider>
  );
}
